CREATE TABLE [dbo].[Users]
(
	[Id] INT IDENTITY(1,1) NOT NULL, 
	[Email] NVARCHAR(256) NOT NULL,
	[EmailNormalized] NVARCHAR(256) NOT NULL,
	[PswHash] NVARCHAR(MAX) NOT NULL	

	CONSTRAINT [PK_UserId] PRIMARY KEY CLUSTERED ([Id] ASC)
);
